const placesData = [
    {
        id: 1,
        name: 'Café Icarus',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Ideal place to have breakfast and brunch with your friends. They are known for their cold brew coffee.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cafe+Icarus+Guadalajara'
    },
    {
        id: 2,
        name: 'Gaspar',
        category: 'Restaurants',
        description: 'Top-rated spots for gourmet burgers and a great bar selection',
        vegetarianOptions: false,
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Gaspar+Punto+Sao+Paulo+Guadalajara'
    },
    {
        id: 3,
        name: 'Cantalú',
        category: 'Restaurants',
        description: 'A cozy health-focused café specializing in baguettes, chapatas, and "Vaketos" (unique keto-friendly desserts).',
        speaksEnglish: true,
        rating: 4.6,
        vegetarianOptions: true,
        imageUrl: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cantalu+Guadalajara'
    },
    {
        id: 4,
        name: 'Caserol',
        category: 'Restaurants',
        description: 'A charming, "cabin-style" restaurant in Midtown known for its breakfast, high-quality bread, and creative presentation.',
        speaksEnglish: false,
        rating: 4.2,
        vegetarianOptions: true,
        imageUrl: 'https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Caserol+Midtown+Guadalajara'
    },
    {
        id: 5,
        name: 'Campomar',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Excellent contemporary Nayarit-style seafood restaurant, perfect for a high-end lunch.',
        rating: 4.9,
        speaksEnglish: true,
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/56/dc/23/campomar-punto-sur.jpg?w=1400&h=-1&s=1',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Campomar+Andares+Guadalajara'
    },
    {
        id: 6,
        name: 'Kaneishi',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Reliable options for sushi and Japanese-inspired bowls.',
        rating: 3.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kaneishi+Guadalajara'
    },
    {
        id: 7,
        name: 'Tacos Providencia',
        vegetarianOptions: false,
        category: 'Restaurants',
        description: 'A local institution. They are famous for their tacos de labio, lengua, and adobada, served with a legendary green salsa.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Providencia+Guadalajara'
    },
    {
        id: 8,
        name: 'Tortas Toño',
        name: 'Tortas Toño',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'One of the most famous chains for Tortas Ahogadas (pork sandwiches drowned in tomato and chili sauce).',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAEX5l9svdmUBRpS-GPK9t0l11OmRnpCvbfFoU-o5VkwHilUAeYMSlmoacbSGuaqR2E-i4Y9ATQXtstDcKk_7astSXeEKs7a8AsCfp-DpFULXOTjvqI60mwIaBmvNmHzZG_FkQDOuw=s762-k-no',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tortas+Toño+Guadalajara'
    },
    {
        id: 9,
        name: 'Porfirios',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A contemporary Mexican restaurant that reinterprets traditional street food into high-end dishes with a vibrant, festive atmosphere',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://porfirios.com.mx/en/wp-content/uploads/sites/2/2023/09/porfirios-mejor-restaurante-mexicano-en-puebla.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Porfirios+Guadalajara'
    },
    {
        id: 10,
        name: 'Nikolaza',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A contemporary Mexican restaurant that reinterprets traditional street food into high-end dishes with a vibrant, festive atmosphere',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNBvmJvPnakWcqRqzXiUgFwUi_ehyqePhpKA&s',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nikolaza+Guadalajara'
    },
    {
        id: 11,
        name: 'Carne Asada Ramón',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Authentic local spot famous for its traditional carne asada and homemade style tortillas.',
        rating: 4.6,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Carne+Asada+Ramon+Guadalajara'
    },
    {
        id: 12,
        name: 'Café Presente',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A cozy café with great coffee and a relaxing atmosphere, perfect for a quiet afternoon or reading.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cafe+Presente+Guadalajara'
    },
    {
        id: 13,
        name: 'Midtown Food Court',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A large modern food court with a variety of affordable options for all tastes, securely located inside Midtown.',
        rating: 4.2,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Midtown+Jalisco+Food+Court'
    },
    {
        id: 14,
        name: 'Gyropolus',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'An authentic Greek restaurant offering delicious gyros, pita bread, and Mediterranean flavors.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://henriquezlara.com/wp-content/uploads/2022/11/GYROPOLUS_HENRIQUEZLARA_03.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Gyropolus+Guadalajara'
    },
    {
        id: 15,
        name: 'Pizza Power',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Located near Punto Sao Paulo, famous for their unique and delicious al pastor meat pizza. An accessible and safe area.',
        rating: 4.4,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pizza+Power+Valparaiso+Guadalajara'
    },
    {
        id: 16,
        name: 'Qin Oriental Food',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Fast, popular, and tasty Chinese food commonly found in major malls and food courts.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Qin+Oriental+Food+Midtown+Guadalajara'
    },
    {
        id: 17,
        name: 'La Artesanal',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A lovely spot featuring artisanal baking, sandwiches, and healthy eating options.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT0FdsoV9fmukYD9whxrdD4YAZALKrJ2miXQ&s',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Artesanal+Midtown+Guadalajara'
    },
    {
        id: 18,
        name: 'Las Flautas Gdl',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A classic local spot at Valparaíso 2372 known for its incredibly crispy and savory Mexican flautas.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2zt1mTwY8duZyODr93bxgdERStSEQwHIICQ&s',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Las+Flautas+Gdl+Valparaiso'
    },
    {
        id: 19,
        name: 'Mar De Cortés',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A premium seafood restaurant offering fresh coastal flavors and a refined dining experience.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1543826173-70651703c5a4?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mar+de+Cortes+Restaurante+Guadalajara'
    },
    {
        id: 20,
        name: 'Tacos Juan',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'An absolute must for locals and foodies looking for incredibly authentic Mexican street tacos.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Juan+Guadalajara'
    },
    {
        id: 21,
        name: 'Las Tortas Ahogadas el Rika',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Local favorite serving hearty, flavorful tortas in a fast, casual environment.',
        rating: 4.2,
        speaksEnglish: false,
        imageUrl: 'https://images.rappi.com.mx/restaurants_logo/1930199984-1720715441335.png',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Las+Tortas+Rika+Guadalajara'
    },
    {
        id: 22,
        name: 'Damiana',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A beautiful blend of coffee culture and literature. A quiet place to enjoy a café y libros.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://scontent.fgdl3-1.fna.fbcdn.net/v/t39.30808-6/527601621_768356262385194_3527198534014599397_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=1d70fc&_nc_ohc=NsEFOHFSHncQ7kNvwHjlMgv&_nc_oc=AdrWSNSYoWmViscE08QqAs5JNszJ99ViKViTmxAETQtIp-OSuuUEo2xEzTBlRKmLnms6uNhemtfSU5EYIC38LSVD&_nc_zt=23&_nc_ht=scontent.fgdl3-1.fna&_nc_gid=vDzb12-lh1ZQEhhG7YWyzQ&_nc_ss=7a3a8&oh=00_Af3ljgeZ4svaI_clS_4efHlh3m7pIEFNPXnIdDfun8_3fA&oe=69DA1D5A',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Damiana+Guadalajara'
    },
    {
        id: 23,
        name: 'Sano Pecado',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Healthy and satisfying. Sano pecado offers guilt-free treats and nutritious main courses.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sano+Pecado+Guadalajara'
    },
    {
        id: 24,
        name: 'Suntory',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'An elegant, high-end teppanyaki and sushi restaurant. Impeccable Japanese service and cuisine.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Suntory+Guadalajara'
    },
    {
        id: 25,
        name: 'Tacos Paris',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Late-night spot popular for straightforward, highly praised street-style tacos.',
        rating: 4.4,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Paris+Guadalajara'
    },
    {
        id: 26,
        name: 'Buffalo Wild Wings',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'American sports bar with a huge selection of wing sauces and multiple screens for sports.',
        rating: 4.1,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1524114664604-cd8133cd67ad?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Buffalo+Wild+Wings+Midtown+Guadalajara'
    },
    {
        id: 27,
        name: 'Mil Caguamas',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Relaxed bar and grill setting offering large portions of seafood and cold beer.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://tb-static.uber.com/prod/image-proc/processed_images/76d581f9b2a1438e428fe24c926577a9/c9252e6c6cd289c588c3381bc77b1dfc.jpeg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mil+Caguamas+Guadalajara'
    },
    {
        id: 28,
        name: 'Tacos Los Asados (López Mateos)',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Convenient and extremely flavorful tacos right off Lopez Mateos, perfect for a quick bite.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Los+Asados+Lopez+Mateos+Guadalajara'
    },
    {
        id: 29,
        name: 'Nohm Cha',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Trendy spot known for serving unique teas, boba, and snacks with a lively aesthetic.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://tb-static.uber.com/prod/image-proc/processed_images/1d9d77183b1241bf5feb1129b31a0365/885ba8620d45ab36746a0e8c7b85ee66.jpeg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nohm+Cha+Guadalajara'
    },
    {
        id: 30,
        name: 'Santa Lucia 66',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'An intimate dining experience with contemporary cuisine and excellent service.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Santa+Lucia+66+Guadalajara'
    },
    {
        id: 31,
        name: 'Tyrano',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Vibrant dining destination offering hearty meals and specialty crafted sandwiches and cuts.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReaAa8HT5Yr38rOKT16Wo1GiijNmn-vUOoUA&s',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tyrano+Guadalajara'
    },
    {
        id: 32,
        name: 'Dainzu',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Very traditional and highly acclaimed Oaxacan food. Perfect to try mole, tlayudas, and authentic regional cuisine.',
        rating: 4.8,
        speaksEnglish: false,
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/fc/d2/47/restaurante-dainzu.jpg?w=600&h=400&s=1',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dainzu+Guadalajara'
    },
    {
        id: 33,
        name: 'Frozé',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A stylish spot focused to frozen beverages and refreshing desserts. Amazing for a hot day.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5qoYA2oT03klp2q82vPwZ2hCXExCMFyM5FA&s',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Froze+Guadalajara'
    },
    {
        id: 34,
        name: 'Vagos',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Cool informal spot with a laidback vibe, great bar foods, and drinks.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQADNwEcQy7bFifFQ34q_ArTxxPhZw2QRy5RQ&s',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Vagos+Guadalajara'
    },
    {
        id: 35,
        name: 'El Terrible Juan',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A hip café and breakfast spot famous for its unique brunch menu and exceptional coffee.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Terrible+Juan+Guadalajara'
    },
    {
        id: 36,
        name: 'Finca los Altos',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A lively traditional dining option offering an array of Mexican dishes and cold drinks.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://scontent.fgdl3-1.fna.fbcdn.net/v/t39.30808-6/469470418_122153362676310220_7980715346035930833_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=1d70fc&_nc_ohc=tnmf6wjAo24Q7kNvwFskLZH&_nc_oc=Adoq0PQdaH-gVL_93KGyjPHKJn8upFqmP-G7fF0RAA-WADzlnlAxKcHK962fM1FAQVMaENJWA7MfIrosuVEra1BO&_nc_zt=23&_nc_ht=scontent.fgdl3-1.fna&_nc_gid=x-bS_IibLVGlGz5W-ehdjg&_nc_ss=7a3a8&oh=00_Af1PAIY82i_A8X53FXKiWPIKPlattTAjLvrMzGTvMxvjeg&oe=69DA44C8',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Alto+Guadalajara'
    },
    {
        id: 37,
        name: 'La Lira',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'An iconic butcher shop that has recently opened a fantastic restaurant upstairs serving their high-quality meats.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Lira+Guadalajara'
    },
    {
        id: 38,
        name: 'Sushi Central',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Trendy sushi spot with fresh ingredients and unique Mexican-inspired sushi rolls and bowls.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sushi+Central+Guadalajara'
    },
    {
        id: 39,
        name: 'Negroni',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A stylish upscale spot in Midtown serving fine Italian cuisine and excellently crafted cocktails.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Negroni+Midtown+Guadalajara'
    },
    {
        id: 40,
        name: 'Nuevo Mundo - Plaza del Sol',
        category: 'Clothing',
        priceRange: '$$',
        description: 'A traditional and reliable department store offering a vast array of clothing, fabrics, and household goods located at Plaza del Sol.',
        rating: 4.1,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nuevo+Mundo+Plaza+del+Sol+Guadalajara'
    },
    {
        id: 41,
        name: 'Lefties',
        category: 'Clothing',
        priceRange: '$',
        description: 'Affordable fast-fashion brand offering trendy clothing and basics. Great for stylish pieces on a budget.',
        rating: 4.0,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lefties+Guadalajara'
    },
    {
        id: 42,
        name: 'Cuidado con el Perro',
        category: 'Clothing',
        priceRange: '$',
        description: 'Highly popular Mexican fast-fashion brand famous for casual wear, graphic tees, and incredibly accessible prices.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://scontent.fgdl3-1.fna.fbcdn.net/v/t39.30808-6/590802978_1456846999782091_8201110300015074117_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=13d280&_nc_ohc=hYiFdRQgedEQ7kNvwE75ZPj&_nc_oc=Adpax4v-1sloMUCFihpH12BHeYaUVF_KJb84utmZO3rxWMORvhBVtiZZ5dkt-2rd6NJhAB895NTVTAnjEL_BrGgF&_nc_zt=23&_nc_ht=scontent.fgdl3-1.fna&_nc_gid=I2H9T51uHWgWA-fCx10k8Q&_nc_ss=7a3a8&oh=00_Af3aDq8MnAnF2k22PS_uEVhgLZwklrFOCuRdFOIJsRZJiQ&oe=69DA0DF9',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cuidado+con+el+Perro+Guadalajara'
    },
    {
        id: 43,
        name: 'Zara',
        category: 'Clothing',
        priceRange: '$$',
        description: 'Well-known international fast-fashion retailer providing stylish and contemporary clothing for men and women.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://imagenes.elpais.com/resizer/v2/UNPXMS3K45E4BN75UMZNXHNXTU.jpg?auth=f203c4115873db07847bc2f588390dc58a242aae464d69e5059832becfcc8160&width=1960&height=1470&focal=2469%2C338',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Zara+Guadalajara'
    },
    {
        id: 44,
        name: 'Pull and Bear',
        category: 'Clothing',
        priceRange: '$$',
        description: 'Trendy, youth-focused brand with a casual aesthetic, offering urban clothing and accessories.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://galeriasgdl.mx/wp-content/uploads/2023/08/PULL-BEAR.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pull+and+Bear+Guadalajara'
    },
    {
        id: 45,
        name: 'Shasa',
        category: 'Clothing',
        priceRange: '$$',
        description: 'A prominent fashion retailer offering stylish, modern, and youthful women's apparel and accessories.',
        rating: 4.2,
        speaksEnglish: false,
        imageUrl: 'https://assets.hotfashion.mx/accounts/2/events/4/editions/34/blogArticles/575/media/951b200d-6288-401b-acc5-b39667ccfe85.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Shasa+Guadalajara'
    },
    {
        id: 46,
        name: 'LOB (Sucursal Midtown Jalisco)',
        category: 'Clothing',
        priceRange: '$$',
        description: 'LOB is a renowned Mexican fashion brand focusing on chic, seasonal, and highly stylish clothing for modern tastes.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=LOB+Midtown+Jalisco+Guadalajara'
    },
    {
        id: 47,
        name: 'Studio F',
        category: 'Clothing',
        priceRange: '$$$',
        description: 'High-quality Colombian brand highly acclaimed for their phenomenally fitting jeans and premium women's clothing.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Studio+F+Guadalajara'
    },
    {
        id: 48,
        name: 'Cloe',
        category: 'Clothing',
        priceRange: '$$',
        description: 'One of the most important Mexican brands for premium handbags, luggage, shoes, and fashionable everyday accessories.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://media.fashionnetwork.com/cdn-cgi/image/fit=contain,width=1000,height=1000,format=auto/m/03dd/d1db/0750/abc2/2370/a2a8/0373/6b5a/1dac/6f82/6f82.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cloe+Guadalajara'
    },
    {
        id: 49,
        name: 'Julio',
        category: 'Clothing',
        priceRange: '$$$',
        description: 'Leading Mexican fashion brand dedicated to incredibly elegant and professional women's apparel and sophisticated dresses.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1560243563-062bfc001d68?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Julio+Boutique+Guadalajara'
    },
    {
        id: 50,
        name: 'BM Saloon',
        category: 'Hair Salons',
        description: 'An aesthetic center specializing in creative hair styling, image consulting, and professional hair care. Located in the upscale Italia Providencia neighborhood.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=BM+Saloon+Lopez+Mateos+Guadalajara'
    },
    {
        id: 51,
        name: 'Neurone Salón',
        category: 'Hair Salons',
        description: 'A modern, full-service salon offering precision haircuts, professional coloring, and expert styling in a contemporary environment in Zapopan.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Neurone+Salon+Zapopan+Guadalajara'
    },
    {
        id: 52,
        name: 'Criminal Chic',
        category: 'Hair Salons',
        description: 'A high-end, trendy author salon specializing in personalized cuts and creative styling. Very popular with the expat community in Ladrón de Guevara.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Criminal+Chic+Joaquin+Angulo+Guadalajara'
    },
    {
        id: 53,
        name: 'Maria Sotho',
        category: 'Hair Salons',
        description: 'A boutique aesthetic center offering personalized hair and image services in an intimate, professional setting in Jardines Alcalde.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://scontent.fgdl10-1.fna.fbcdn.net/v/t39.30808-6/312802464_2037269859791049_4936027710920592520_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=1d70fc&_nc_ohc=UofDn_LEBd0Q7kNvwH6jk1E&_nc_oc=AdrrcqjUE4d5DcUpalA1lZDodpmvAtp-tZqH_5r6_YDGIbvNaHJ5tETeB87UNQpfMx03ckd1oXZCkP09Zt6UqMgt&_nc_zt=23&_nc_ht=scontent.fgdl10-1.fna&_nc_gid=nr5Me1FSWn-5D60vrrv3Tw&_nc_ss=7a3a8&oh=00_Af3o3i9-gZiMF5JTY76JFubQYx_ZV7aOW-j3xMF8CVSapQ&oe=69DA2E17',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Maria+Sotho+Guadalajara'
    },
    {
        id: 54,
        name: "Mom & Son's Salon",
        category: 'Hair Salons',
        description: 'A highly-rated barbershop and beauty salon loved by locals and expats alike. Known for consistent quality cuts and a welcoming atmosphere in Ladrón de Guevara.',
        rating: 4.8,
        speaksEnglish: false,
        imageUrl: 'https://mid-townjalisco.com.mx/wp-content/uploads/elementor/thumbs/MomSons-r0rzs60fvy5u71mmkve7wgciq6p1mtomvbom4q096w.webp',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mom+and+Sons+Salon+Guadalajara'
    },
    {
        id: 55,
        name: 'El Silloncito',
        category: 'Hair Salons',
        description: 'The go-to children\'s hair salon in Guadalajara, with a fun and colorful environment designed to make haircuts enjoyable for kids of all ages.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://elsilloncito.com.mx/img/design/logo-og.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Silloncito+Americana+Guadalajara'
    },
    {
        id: 56,
        name: 'Hospital Veterinario Guadalajara',
        category: 'Vets',
        description: '24/7 full-service veterinary hospital offering surgery, radiology, internal medicine, and a pharmacy. One of the most complete emergency animal hospitals in the city.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://scontent.fgdl10-1.fna.fbcdn.net/v/t39.30808-6/469793584_573105348801376_5322662547425049532_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=2a1932&_nc_ohc=hPJK0ByXiHoQ7kNvwGkWV2c&_nc_oc=AdpVlIkb14m-wcFv1RGEZfxMeevFktskQa-hjr6MnPsnCyWDbkMDM3BWAVf_qYMnM-1sz8DWpWxJkKqUNZxiYyGB&_nc_zt=23&_nc_ht=scontent.fgdl10-1.fna&_nc_gid=nENkIAntQZKeuczTASMQ7g&_nc_ss=7a3a8&oh=00_Af0dHfV-5-eh-NqR8qIjyZnirG6wX9Ivp9KPN2NX8a0zhg&oe=69DA190F',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Veterinario+Guadalajara+Lopez+Mateos'
    },
    {
        id: 57,
        name: 'El Doc',
        category: 'Vets',
        description: 'Boutique veterinary clinic offering general consultations, grooming, and internal medicine. Known for personalized, high-quality care in an upscale environment.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Doc+veterinaria+Guadalajara'
    },
    {
        id: 58,
        name: 'Hospital Veterinario Arboledas',
        category: 'Vets',
        description: 'A large-scale 24-hour veterinary hospital specializing in orthopedics, intensive care, and complex surgeries. Trusted by expats for emergency and specialist care.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Veterinario+Arboledas+Guadalajara'
    },
    {
        id: 59,
        name: 'Clínica Veterinaria Solares',
        category: 'Vets',
        description: 'A modern veterinary clinic in the Solares residential complex offering dentistry, dermatology, and specialized aesthetic care for pets in a calm, professional setting.',
        rating: 4.1,
        speaksEnglish: true,
        imageUrl: 'https://mivet.com/wp-content/uploads/2024/10/clinica_solares_2.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Clinica+Veterinaria+Solares+Zapopan'
    },
    {
        id: 60,
        name: 'VetPets',
        category: 'Vets',
        description: 'A reliable general veterinary hospital providing preventive medicine, vaccinations, and surgery. Well located near the university district.',
        rating: 4.1,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=VetPets+Hospital+Veterinario+Guadalajara'
    },
    {
        id: 61,
        name: 'PET Clinik',
        category: 'Vets',
        description: 'A high-end, modern veterinary facility offering advanced surgery, laboratory diagnostics, and 24-hour emergency care. Top choice for expats seeking premium pet healthcare.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://scontent.fgdl3-1.fna.fbcdn.net/v/t39.30808-6/358664365_743835694413785_6330227947454179697_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=1d70fc&_nc_ohc=LBd_hxJNSwQQ7kNvwH6cE_t&_nc_oc=AdpeXGu1tguzIMbYuqzHW1lGMkEhV-rKnfGKdDmfFvbeJ9QF3SDDmImb78XooCBBk7hYWGr4xaX9vXQc2heKG1Sr&_nc_zt=23&_nc_ht=scontent.fgdl3-1.fna&_nc_gid=Oy9UsHch9rhwIlX-nVnSsg&_nc_ss=7a3a8&oh=00_Af18_cwowZeG4eJNFeC4PNBwBB0cRhTl-hI9-eJhDfdSiQ&oe=69DA4971',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=PET+Clinik+Hospital+Veterinario+Zapopan'
    },
    {
        id: 62,
        name: 'Veterinaria Moro',
        category: 'Vets',
        description: 'A specialized veterinary diagnostic center providing hematology, laboratory studies, and expert clinical analysis. Known for its highly professional and thorough approach.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Servicios+Veterinarios+Moro+Guadalajara'
    },
    {
        id: 63,
        name: 'Lomont Hospital Veterinario',
        category: 'Vets',
        description: 'A specialized veterinary hospital focused on traumatology, orthopedics, and neurology. One of the few facilities in the city offering this level of specialist care.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://scontent.fgdl10-1.fna.fbcdn.net/v/t39.30808-6/342182717_621022726189007_6836651587672774337_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=1d70fc&_nc_ohc=qeeB32VfMZEQ7kNvwELNVXs&_nc_oc=Adr8gv9x7UOmhb885Q5Oc--S5fT4UnaWVgow4qXb-PtvP1Chz-SM9Cn5JZ2IUgkRKQ6Iu4jpEc3aCYsjKDDeE_qO&_nc_zt=23&_nc_ht=scontent.fgdl10-1.fna&_nc_gid=zf0jc6GdpqctrugPZ8PYRQ&_nc_ss=7a3a8&oh=00_Af0r8w6tZayLlZVzhqGcYUTULI7IhiuTZ5Dsa3iDrPIzbA&oe=69DA3E41',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lomont+Hospital+Veterinario+Guadalajara'
    },
    {
        id: 64,
        name: "Veterinaria Cat's & Dog's",
        category: 'Vets',
        description: 'A friendly neighborhood veterinary clinic offering primary care, general consultations, vaccinations, and grooming services for cats and dogs.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=600&q=80',
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Veterinaria+Cats+and+Dogs+Guadalajara"
    },
    {
        id: 65,
        name: 'Mexico Americano Hospital',
        category: 'Clinics',
        description: 'A reliable hospital providing general surgery, maternity care, and family medicine.',
        rating: 3.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Mexico+Americano+Guadalajara'
    },
    {
        id: 66,
        name: 'Hospital Puerta de Hierro',
        category: 'Clinics',
        description: 'A high-end medical center specializing in advanced surgeries, cardiology, and sports medicine.',
        rating: 4.0,
        speaksEnglish: true,
        imageUrl: 'https://i0.wp.com/hospitalespuertadehierro.com/wp-content/uploads/2020/04/Ambulatoria-scaled.jpg?fit=2560%2C1607&ssl=1',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Puerta+de+Hierro+Andares+Guadalajara'
    },
    {
        id: 67,
        name: 'Hospital San Javier',
        category: 'Clinics',
        description: 'A full-service hospital known for cancer treatment, heart surgery, and 24/7 emergencies.',
        rating: 3.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+San+Javier+Guadalajara'
    },
    {
        id: 68,
        name: 'Hospital San Francisco de Asis',
        category: 'Clinics',
        description: 'A professional facility focused on general medical care, internal medicine, and surgery.',
        rating: 3.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+San+Francisco+de+Asis+Guadalajara'
    },
    {
        id: 69,
        name: 'Hospital Jardines',
        category: 'Clinics',
        description: 'A private hospital known for orthopedic surgery, weight loss procedures, and emergencies.',
        rating: 3.6,
        speaksEnglish: false,
        imageUrl: 'https://img.bookimed.com/clinic_webp/6436e4b1d7617.webp',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Jardines+Guadalajara'
    },
    {
        id: 70,
        name: 'Clinica Ginecologica Providencia',
        category: 'Clinics',
        description: 'A smaller medical center offering outpatient surgery, laboratory tests, and general check-ups.',
        rating: 2.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Clinica+Ginecologica+Providencia+Guadalajara'
    },

    {
        id: 72,
        name: 'Ninus Pediatric Hospital',
        category: 'Clinics',
        description: 'A hospital built specifically for the medical needs of children.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://scontent.fgdl3-1.fna.fbcdn.net/v/t39.30808-6/576931600_860636499958176_903378426246504629_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=1d70fc&_nc_ohc=RZrIy0WnwAIQ7kNvwEnwX64&_nc_oc=Adoffdq7WZrpaP-3SJxdKRwi4VC6uxextM06-jJ1rdyKGQrLYNEuZqa-CD8vK8E6_seJEZ1wxm8Wqp-A0fKyClm5&_nc_zt=23&_nc_ht=scontent.fgdl3-1.fna&_nc_gid=3bT2Puqi6jNIYy6CF6hEoA&_nc_ss=7a3a8&oh=00_Af1c3ZcUr5q5VWRUjvVlg5A8I9xPbuKxjR5VrV2ZU-X6vg&oe=69DA44B4',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ninus+Centro+Integral+Pediatrico+Guadalajara'
    }, {
        id: 73,
        name: 'La Unidad de Patología',
        category: 'Clinics',
        description: 'A premier diagnostic building for blood tests, biopsies, and advanced medical imaging.',
        rating: 3.9,
        speaksEnglish: false,
        imageUrl: 'https://upc.com.mx/img/design/backgrounds/sucursales.jpg',
        mapsUrl: 'https://www.google.com/maps/place/Unidad+de+Patolog%C3%ADa+Cl%C3%ADnica+e+Imagenolog%C3%ADa/@20.6790268,-103.4106715,13z/data=!3m1!5s0x8428ae1162d94179:0x115b1e977b881e1e!4m10!1m2!2m1!1sLa+Unidad+de+Patologia+Guadalajara!3m6!1s0x8428ae6f337d958d:0xcb076a23316a80c1!8m2!3d20.6790268!4d-103.3756526!15sCiJMYSBVbmlkYWQgZGUgUGF0b2xvZ2lhIEd1YWRhbGFqYXJhWiQiImxhIHVuaWRhZCBkZSBwYXRvbG9naWEgZ3VhZGFsYWphcmGSAQttZWRpY2FsX2xhYpoBI0NoWkRTVWhOTUc5blMwVkpRMEZuVFVOWk1uRnRSRXBSRUFF4AEA-gEECGsQNg!16s%2Fg%2F1tx1thwk?entry=ttu&g_ep=EgoyMDI2MDQwMS4wIKXMDSoASAFQAw%3D%3D'
    },
    {
        id: 74,
        name: 'Arena Astros de Jalisco',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'Cheer for the local professional basketball team! A vibrant, safe arena perfect for sports enthusiasts and families.',
        rating: 4.8,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Arena+Astros+Jalisco+Guadalajara'
    },
    {
        id: 75,
        name: 'Parque Avila Camacho',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'A beautiful public park offering boat rides, playgrounds, and plenty of green spaces. Extremely familiar and great for an outdoor picnic.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://www.turimexico.com/wp-content/uploads/2017/10/Parque-%C3%81vila-Camacho-en-Guadalajara.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Parque+Avila+Camacho+Guadalajara'
    },
    {
        id: 76,
        name: 'MAZ - Museo de Arte de Zapopan',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'Contemporary art museum in the heart of Zapopan. Offers dynamic exhibitions and cultural workshops for all ages.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://maz.zapopan.gob.mx/wp-content/uploads/2024/08/fachada_2024_.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Museo+de+Arte+de+Zapopan'
    },
    {
        id: 77,
        name: 'Zoológico Guadalajara',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'One of the most important zoos in Latin America. Features a safari, aquarium, and panoramic cable car ride.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://cdn.milenio.com/uploads/media/2023/02/04/zoologico-guadalajara-especial-1.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Zoologico+Guadalajara'
    },
    {
        id: 78,
        name: 'Parque Los Colomos',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'An iconic forest inside the city. Ideal for jogging, feeding squirrels, and exploring proper Japanese gardens.',
        rating: 4.8,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Parque+Los+Colomos+Guadalajara'
    },
    {
        id: 79,
        name: 'Pista de Patinaje Bugambilias',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'An indoor ice skating rink located in the Bugambilias mall. Perfect for cooling down and family fun.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://lh5.googleusercontent.com/-UZidP8xjixs/WWgRldPSHXI/AAAAAAAAAR8/wyC3tK0V1r8pUpidVQ9qNZ0fG-bFB0WYgCLIBGAYYCw/photo.jpg',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pista+de+Hielo+Bugambilias+Guadalajara'
    },
    {
        id: 80,
        name: 'La Cineteca FICG',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'The premier center for cinema showcasing independent, international, and mainstream films. Completely appropriate for the entire family depending on the screening.',
        rating: 4.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cineteca+FICG+Guadalajara'
    },
    {
        id: 81,
        name: 'KidZania',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'An interactive mini-city built for kids to role-play professions. Extremely engaging and educational!',
        rating: 4.8,
        speaksEnglish: false,
        imageUrl: 'https://cdn.sanity.io/images/vr0czzef/production/4b42a61c9238efc0169af545ade63915f6166bf5-1400x800.png?w=3840&h=2194&fm=webp&q=80&fit=max&auto=format',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=KidZania+Guadalajara'
    },
    {
        id: 82,
        name: 'Motion Boulder',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'A vibrant indoor climbing and bouldering gym. Great for active families and people looking for a physical challenge.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Motion+Boulder+Guadalajara'
    },
    {
        id: 83,
        name: 'Cinery',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'An upscale, comfortable cinema experience offering great food and immersive movie viewings for a relaxed evening.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cinery+Guadalajara'
    },
    {
        id: 84,
        name: 'Biblioteca Pública del Estado',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'A massive, modern public library containing vast collections of books. It has dedicated reading zones and children\'s areas.',
        rating: 4.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Biblioteca+Publica+del+Estado+de+Jalisco'
    },
    {
        id: 85,
        name: 'Vía RecreActiva',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'Every Sunday, major avenues are closed to cars. People come out to cycle, rollerblade, and walk their pets in a completely festive and safe setting.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Via+RecreActiva+Guadalajara'
    }
];
const eventsData = [
    {
        id: 86,
        title: 'Festival Internacional de Cine en Guadalajara',
        culture: 'Mexican / International',
        date: 'April 17â€“25, 2026',
        location: 'Cineteca FICG',
        description: 'One of the most important film festivals in Latin America bringing together filmmakers, actors, and cinema enthusiasts for screenings and networking.',
        imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cineteca+FICG'
    },
    {
        id: 87,
        title: 'Diwali Festival de las Luces',
        culture: 'Indian',
        date: 'November 2026',
        location: 'Olimpo Salón de Eventos',
        description: 'Celebrate the Indian Festival of Lights with traditional food, dance performances, henna art, and spectacular lighting displays presented by the Indian expat community.',
        imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipMg6Qe9cyX8rIowGrzexahNMI4CMbeh-VUiyNW5=s3072-v1',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Olimpo+salon+de+eventos+en+zapopan+guadalajara'
    },
    {
        id: 88,
        title: 'Fiestas de Octubre',
        culture: 'Mexican',
        date: 'October â€“ November 2026',
        location: 'Auditorio Benito Juárez',
        description: 'A massive month-long city-wide celebration showcasing Mexican culture with concerts, regional dances, art exhibits, and a large traditional fair.',
        imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Auditorio+Benito+Juarez'
    },
    {
        id: 89,
        title: 'Otoñobier Fest',
        culture: 'German',
        date: 'Mid-October 2026',
        location: 'Near Parque Metropolitano',
        description: 'Authentic Bavarian beer, pretzels, bratwurst, and traditional German folk music in a huge festive tent.',
        imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPb-FOtNsltqQOy9vlXB3dMVDXrwKuXQwlc_xo-=s3072-v1',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Parque+Metropolitano+Guadalajara'
    },
    {
        id: 90,
        title: 'Romería de la Virgen de Zapopan',
        culture: 'Mexican',
        date: 'October 12, 2026',
        location: 'Guadalajara Cathedral to Basilica of Zapopan',
        description: 'A deeply significant UNESCO recognized cultural procession involving millions of people accompanying the image of the Virgin of Zapopan on an 8km pilgrimage.',
        imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Catedral_de_costado_recibiendo_a_la_Virgen_de_Zapopan.jpg?width=600',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Basilica+de+Zapopan'
    },
];
