const placesData = [
    {
        id: 1,
        name: 'Café Icarus',
        category: 'Restaurants',
        description: 'Ideal place to have breakfast and brunch with your friends.They are known for their cold brew coffe.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cafe+Icarus+Guadalajara'
    },
    {
        id: 2,
        name: 'Gaspar',
        category: 'Restaurants',
        description: 'Top-rated spots for gourmet burgers and a great bar selection',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Gaspar+Punto+Sao+Paulo+Guadalajara'
    },
    {
        id: 3,
        name: 'Cantalú',
        category: 'Restaurants',
        description: 'A cozy health-focused café specializing in baguettes, chapatas, and "Vaketos" (unique keto-friendly desserts).',
        speaksEnglish: true,
        rating: 4.6,
        vegetarianOptions: true,
        imageUrl: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cantalu+Guadalajara'
    },
    {
        id: 4,
        name: 'Caserol',
        category: 'Restaurants',
        description: 'A charming, "cabin-style" restaurant in Midtown known for its breakfast, high-quality bread, and creative presentation.',
        speaksEnglish: false,
        rating: 4.2,
        vegetarianOptions: true,
        imageUrl: 'https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Caserol+Midtown+Guadalajara'
    },
    {
        id: 5,
        name: 'Campomar',
        category: 'Restaurants',
        description: 'Excellent contemporary Nayarit-style seafood restaurant, perfect for a high-end lunch.',
        rating: 4.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1615141982883-c7da0e69f591?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Campomar+Andares+Guadalajara'
    },
    {
        id: 6,
        name: 'Kaneishi',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Reliable options for sushi and Japanese-inspired bowls.',
        rating: 3.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kaneishi+Guadalajara'
    },
    {
        id: 7,
        name: 'Tacos Providencia',
        vegetarianOptions: false,
        category: 'Restaurants',
        description: 'A local institution. They are famous for their tacos de labio, lengua, and adobada, served with a legendary green salsa.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Providencia+Guadalajara'
    },
    {
        id: 8,
        name: 'Tortas Toño',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'One of the most famous chains for Tortas Ahogadas (pork sandwiches drowned in tomato and chili sauce).',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tortas+Tono+Guadalajara'
    },
    {
        id: 9,
        name: 'Porfirios',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A contemporary Mexican restaurant that reinterprets traditional street food into high-end dishes with a vibrant, festive atmosphere',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Porfirios+Guadalajara'
    },
    {
        id: 10,
        name: 'Nikolaza',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A contemporary Mexican restaurant that reinterprets traditional street food into high-end dishes with a vibrant, festive atmosphere',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1563514995968-07d4b4dd5fa5?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nikolaza+Guadalajara'
    },
    {
        id: 11,
        name: 'Carne Asada Ramón',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Authentic local spot famous for its traditional carne asada and homemade style tortillas.',
        rating: 4.6,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Carne+Asada+Ramon+Guadalajara'
    },
    {
        id: 12,
        name: 'Café Presente',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A cozy café with great coffee and a relaxing atmosphere, perfect for a quiet afternoon or reading.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cafe+Presente+Guadalajara'
    },
    {
        id: 13,
        name: 'Midtown Food Court',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A large modern food court with a variety of affordable options for all tastes, securely located inside Midtown.',
        rating: 4.2,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Midtown+Jalisco+Food+Court'
    },
    {
        id: 14,
        name: 'Gyropolus',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'An authentic Greek restaurant offering delicious gyros, pita bread, and Mediterranean flavors.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Gyropolus+Guadalajara'
    },
    {
        id: 15,
        name: 'Pizza Power',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Located near Punto Sao Paulo, famous for their unique and delicious al pastor meat pizza. An accessible and safe area.',
        rating: 4.4,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pizza+Power+Valparaiso+Guadalajara'
    },
    {
        id: 17,
        name: 'Qin Oriental Food',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Fast, popular, and tasty Chinese food commonly found in major malls and food courts.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Qin+Oriental+Food+Midtown+Guadalajara'
    },
    {
        id: 18,
        name: 'La Artesanal',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A lovely spot featuring artisanal baking, sandwiches, and healthy eating options.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1495474472200-c8f2ba1cbdd0?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Artesanal+Midtown+Guadalajara'
    },
    {
        id: 19,
        name: 'Las Flautas Gdl',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A classic local spot at Valparaíso 2372 known for its incredibly crispy and savory Mexican flautas.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Las+Flautas+Gdl+Valparaiso'
    },
    {
        id: 20,
        name: 'Mar De Cortés',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A premium seafood restaurant offering fresh coastal flavors and a refined dining experience.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1543826173-70651703c5a4?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mar+de+Cortes+Restaurante+Guadalajara'
    },
    {
        id: 21,
        name: 'Tacos Juan',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'An absolute must for locals and foodies looking for incredibly authentic Mexican street tacos.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Juan+Guadalajara'
    },
    {
        id: 23,
        name: 'Las Tortas Rika',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Local favorite serving hearty, flavorful tortas in a fast, casual environment.',
        rating: 4.2,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Las+Tortas+Rika+Guadalajara'
    },
    {
        id: 24,
        name: 'Damiana',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A beautiful blend of coffee culture and literature. A quiet place to enjoy a café y libros.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1507133750070-44473e5a40a4?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Damiana+Guadalajara'
    },
    {
        id: 25,
        name: 'Sano Pecado',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Healthy and satisfying. Sano pecado offers guilt-free treats and nutritious main courses.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sano+Pecado+Guadalajara'
    },
    {
        id: 26,
        name: 'Suntory',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'An elegant, high-end teppanyaki and sushi restaurant. Impeccable Japanese service and cuisine.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Suntory+Guadalajara'
    },
    {
        id: 27,
        name: 'Tacos Paris',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Late-night spot popular for straightforward, highly praised street-style tacos.',
        rating: 4.4,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Paris+Guadalajara'
    },
    {
        id: 28,
        name: 'Buffalo Wild Wings',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'American sports bar with a huge selection of wing sauces and multiple screens for sports.',
        rating: 4.1,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1524114664604-cd8133cd67ad?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Buffalo+Wild+Wings+Midtown+Guadalajara'
    },
    {
        id: 29,
        name: 'Mil Caguamas',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Relaxed bar and grill setting offering large portions of seafood and cold beer.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1534068307252-eb0ae9ee6820?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mil+Caguamas+Guadalajara'
    },
    {
        id: 30,
        name: 'Tacos Los Asados (López Mateos)',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Convenient and extremely flavorful tacos right off Lopez Mateos, perfect for a quick bite.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Los+Asados+Lopez+Mateos+Guadalajara'
    },
    {
        id: 31,
        name: 'Nohm Cha',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Trendy spot known for serving unique teas, boba, and snacks with a lively aesthetic.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1525648199074-cee30ba79a4a?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nohm+Cha+Guadalajara'
    },
    {
        id: 32,
        name: 'Santa Lucia 66',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'An intimate dining experience with contemporary cuisine and excellent service.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Santa+Lucia+66+Guadalajara'
    },
    {
        id: 33,
        name: 'Tyrano',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Vibrant dining destination offering hearty meals and specialty crafted sandwiches and cuts.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1508737804141-4c3b688e2546?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tyrano+Guadalajara'
    },
    {
        id: 34,
        name: 'Dainzu',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Very traditional and highly acclaimed Oaxacan food. Perfect to try mole, tlayudas, and authentic regional cuisine.',
        rating: 4.8,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dainzu+Guadalajara'
    },
    {
        id: 35,
        name: 'Frozé',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A stylish spot focused to frozen beverages and refreshing desserts. Amazing for a hot day.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1558222218-b7b54eede3f3?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Froze+Guadalajara'
    },
    {
        id: 36,
        name: 'Vagos',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Cool informal spot with a laidback vibe, great bar foods, and drinks.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Vagos+Guadalajara'
    },
    {
        id: 37,
        name: 'El Terrible Juan',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A hip café and breakfast spot famous for its unique brunch menu and exceptional coffee.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Terrible+Juan+Guadalajara'
    },
    {
        id: 38,
        name: 'El Alto',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A lively traditional dining option offering an array of Mexican dishes and cold drinks.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1514326640560-7d063ef2aed5?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Alto+Guadalajara'
    },
    {
        id: 39,
        name: 'La Lira',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'An iconic butcher shop that has recently opened a fantastic restaurant upstairs serving their high-quality meats.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Lira+Carniceria+Guadalajara'
    },
    {
        id: 40,
        name: 'Tacos Al Vapor El Costquito',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Unbeatable comfort food: freshly made "tacos al vapor" (steamed tacos) that are wildly popular locally.',
        rating: 4.6,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Al+Vapor+El+Costquito+Guadalajara'
    },
    {
        id: 44,
        name: 'Sushi Central',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Trendy sushi spot with fresh ingredients and unique Mexican-inspired sushi rolls and bowls.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sushi+Central+Guadalajara'
    },
    {
        id: 45,
        name: 'Negroni',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A stylish upscale spot in Midtown serving fine Italian cuisine and excellently crafted cocktails.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Negroni+Midtown+Guadalajara'
    },
    {
        id: 46,
        name: 'Nuevo Mundo - Plaza del Sol',
        category: 'Clothing',
        priceRange: '$$',
        description: 'A traditional and reliable department store offering a vast array of clothing, fabrics, and household goods located at Plaza del Sol.',
        rating: 4.1,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nuevo+Mundo+Plaza+del+Sol+Guadalajara'
    },
    {
        id: 47,
        name: 'Lefties',
        category: 'Clothing',
        priceRange: '$',
        description: 'Affordable fast-fashion brand offering trendy clothing and basics. Great for stylish pieces on a budget.',
        rating: 4.0,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lefties+Guadalajara'
    },
    {
        id: 48,
        name: 'Cuidado con el Perro',
        category: 'Clothing',
        priceRange: '$',
        description: 'Highly popular Mexican fast-fashion brand famous for casual wear, graphic tees, and incredibly accessible prices.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1528698827591-e19cdd722f0a?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cuidado+con+el+Perro+Guadalajara'
    },
    {
        id: 49,
        name: 'Zara',
        category: 'Clothing',
        priceRange: '$$',
        description: 'Well-known international fast-fashion retailer providing stylish and contemporary clothing for men and women.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1580828369062-81525a7eb84f?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Zara+Guadalajara'
    },
    {
        id: 50,
        name: 'Pull and Bear',
        category: 'Clothing',
        priceRange: '$$',
        description: 'Trendy, youth-focused brand with a casual aesthetic, offering urban clothing and accessories.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1564585222527-c2777a5bc6cb?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pull+and+Bear+Guadalajara'
    },
    {
        id: 51,
        name: 'Shasa (Sasha)',
        category: 'Clothing',
        priceRange: '$$',
        description: 'A prominent fashion retailer offering stylish, modern, and youthful womens apparel and accessories.',
        rating: 4.2,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Shasa+Guadalajara'
    },
    {
        id: 52,
        name: 'LOB (Sucursal Midtown Jalisco)',
        category: 'Clothing',
        priceRange: '$$',
        description: 'LOB is a renowned Mexican fashion brand focusing on chic, seasonal, and highly stylish clothing for modern tastes.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=LOB+Midtown+Jalisco+Guadalajara'
    },
    {
        id: 53,
        name: 'Studio F',
        category: 'Clothing',
        priceRange: '$$$',
        description: 'High-quality Colombian brand highly acclaimed for their phenomenally fitting jeans and premium womens clothing.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Studio+F+Guadalajara'
    },
    {
        id: 54,
        name: 'Cloe',
        category: 'Clothing',
        priceRange: '$$',
        description: 'One of the most important Mexican brands for premium handbags, luggage, shoes, and fashionable everyday accessories.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cloe+Guadalajara'
    },
    {
        id: 55,
        name: 'Julio',
        category: 'Clothing',
        priceRange: '$$$',
        description: 'Leading Mexican fashion brand dedicated to incredibly elegant and professional womens apparel and sophisticated dresses.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1560243563-062bfc001d68?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Julio+Boutique+Guadalajara'
    },
    {
        id: 56,
        name: 'BM Saloon',
        category: 'Hair Salons',
        description: 'An aesthetic center specializing in creative hair styling, image consulting, and professional hair care. Located in the upscale Italia Providencia neighborhood.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=BM+Saloon+Lopez+Mateos+Guadalajara'
    },
    {
        id: 57,
        name: 'Neurone Salón',
        category: 'Hair Salons',
        description: 'A modern, full-service salon offering precision haircuts, professional coloring, and expert styling in a contemporary environment in Zapopan.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Neurone+Salon+Zapopan+Guadalajara'
    },
    {
        id: 58,
        name: 'Criminal Chic',
        category: 'Hair Salons',
        description: 'A high-end, trendy author salon specializing in personalized cuts and creative styling. Very popular with the expat community in Ladrón de Guevara.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Criminal+Chic+Joaquin+Angulo+Guadalajara'
    },
    {
        id: 59,
        name: 'Maria Sotho',
        category: 'Hair Salons',
        description: 'A boutique aesthetic center offering personalized hair and image services in an intimate, professional setting in Jardines Alcalde.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138daaa4e4e1?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Maria+Sotho+Guadalajara'
    },
    {
        id: 60,
        name: "Mom & Son's Salon",
        category: 'Hair Salons',
        description: 'A highly-rated barbershop and beauty salon loved by locals and expats alike. Known for consistent quality cuts and a welcoming atmosphere in Ladrón de Guevara.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mom+and+Sons+Salon+Guadalajara'
    },
    {
        id: 61,
        name: 'El Silloncito',
        category: 'Hair Salons',
        description: 'The go-to children\'s hair salon in Guadalajara, with a fun and colorful environment designed to make haircuts enjoyable for kids of all ages.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Silloncito+Americana+Guadalajara'
    },
    {
        id: 62,
        name: 'Hospital Veterinario Guadalajara',
        category: 'Vets',
        description: '24/7 full-service veterinary hospital offering surgery, radiology, internal medicine, and a pharmacy. One of the most complete emergency animal hospitals in the city.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Veterinario+Guadalajara+Lopez+Mateos'
    },
    {
        id: 63,
        name: 'El Doc',
        category: 'Vets',
        description: 'Boutique veterinary clinic offering general consultations, grooming, and internal medicine. Known for personalized, high-quality care in an upscale environment.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Doc+veterinaria+Guadalajara'
    },
    {
        id: 64,
        name: 'Hospital Veterinario Arboledas',
        category: 'Vets',
        description: 'A large-scale 24-hour veterinary hospital specializing in orthopedics, intensive care, and complex surgeries. Trusted by expats for emergency and specialist care.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Veterinario+Arboledas+Guadalajara'
    },
    {
        id: 65,
        name: 'Clínica Veterinaria Solares',
        category: 'Vets',
        description: 'A modern veterinary clinic in the Solares residential complex offering dentistry, dermatology, and specialized aesthetic care for pets in a calm, professional setting.',
        rating: 4.1,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Clinica+Veterinaria+Solares+Zapopan'
    },
    {
        id: 66,
        name: 'VetPets',
        category: 'Vets',
        description: 'A reliable general veterinary hospital providing preventive medicine, vaccinations, and surgery. Well located near the university district.',
        rating: 4.1,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=VetPets+Hospital+Veterinario+Guadalajara'
    },
    {
        id: 67,
        name: 'PET Clinik',
        category: 'Vets',
        description: 'A high-end, modern veterinary facility offering advanced surgery, laboratory diagnostics, and 24-hour emergency care. Top choice for expats seeking premium pet healthcare.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1548767797-d8c844163c4a?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=PET+Clinik+Hospital+Veterinario+Zapopan'
    },
    {
        id: 68,
        name: 'Veterinaria Moro',
        category: 'Vets',
        description: 'A specialized veterinary diagnostic center providing hematology, laboratory studies, and expert clinical analysis. Known for its highly professional and thorough approach.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Servicios+Veterinarios+Moro+Guadalajara'
    },
    {
        id: 69,
        name: 'Lomont Hospital Veterinario',
        category: 'Vets',
        description: 'A specialized veterinary hospital focused on traumatology, orthopedics, and neurology. One of the few facilities in the city offering this level of specialist care.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lomont+Hospital+Veterinario+Guadalajara'
    },
    {
        id: 70,
        name: "Veterinaria Cat's & Dog's",
        category: 'Vets',
        description: 'A friendly neighborhood veterinary clinic offering primary care, general consultations, vaccinations, and grooming services for cats and dogs.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=600&q=80',
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Veterinaria+Cats+and+Dogs+Guadalajara"
    },
    {
        id: 71,
        name: 'México Americano Hospital',
        category: 'Clinics',
        description: 'A reliable hospital providing general surgery, maternity care, and family medicine.',
        rating: 3.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Mexico+Americano+Guadalajara'
    },
    {
        id: 72,
        name: 'Hospital Puerta de Hierro',
        category: 'Clinics',
        description: 'A high-end medical center specializing in advanced surgeries, cardiology, and sports medicine.',
        rating: 4.0,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1538108149393-cebb47ac7984?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Puerta+de+Hierro+Andares+Guadalajara'
    },
    {
        id: 73,
        name: 'Hospital San Javier',
        category: 'Clinics',
        description: 'A full-service hospital known for cancer treatment, heart surgery, and 24/7 emergencies.',
        rating: 3.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+San+Javier+Guadalajara'
    },
    {
        id: 74,
        name: 'Hospital San Francisco de Asís',
        category: 'Clinics',
        description: 'A professional facility focused on general medical care, internal medicine, and surgery.',
        rating: 3.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+San+Francisco+de+Asis+Guadalajara'
    },
    {
        id: 75,
        name: 'Hospital Jardines',
        category: 'Clinics',
        description: 'A private hospital known for orthopedic surgery, weight loss procedures, and emergencies.',
        rating: 3.6,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1502740479091-635887520276?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Jardines+Guadalajara'
    },
    {
        id: 76,
        name: 'Clinica Ginecologica Providencia',
        category: 'Clinics',
        description: 'A smaller medical center offering outpatient surgery, laboratory tests, and general check-ups.',
        rating: 2.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Clinica+Ginecologica+Providencia+Guadalajara'
    },
    {
        id: 77,
        name: 'Real San José Hospital',
        category: 'Clinics',
        description: 'A modern facility providing high-tech imaging, maternity services, and specialized consultations.',
        rating: 3.4,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1560205001-a76cd1fba76d?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/place/Hospital+Real+San+Jose/@20.6973647,-103.4195811,14z/data=!3m1!5s0x8428ae889fa0fa41:0x4d14c68df9722d93!4m10!1m2!2m1!1sHospital+Real+San+Jose+Guadalajara!3m6!1s0x8428ae88a051e085:0xba5be62f4811d11b!8m2!3d20.6728373!4d-103.4095175!15sCiJIb3NwaXRhbCBSZWFsIFNhbiBKb3NlIEd1YWRhbGFqYXJhkgEQcHJpdmF0ZV9ob3NwaXRhbOABAA!16s%2Fg%2F1tdp9ygs?entry=ttu&g_ep=EgoyMDI2MDQwMS4wIKXMDSoASAFQAw%3D%3D'
    },
    {
        id: 78,
        name: 'Ninus Pediatric Hospital',
        category: 'Clinics',
        description: 'A hospital built specifically for the medical needs of children.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1542898953-ce20cd292558?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ninus+Centro+Integral+Pediatrico+Guadalajara'
    },
    {
        id: 79,
        name: 'San Jose Valle Real Hospital',
        category: 'Clinics',
        description: 'A specialized branch focused on pediatric emergencies and children\'s health check-ups.',
        rating: 3.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1596541223130-5d56447ceb6c?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hospital+Real+San+Jose+Valle+Real+Guadalajara'
    },
    {
        id: 80,
        name: 'La Unidad de Patología',
        category: 'Clinics',
        description: 'A premier diagnostic building for blood tests, biopsies, and advanced medical imaging.',
        rating: 3.9,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/place/Unidad+de+Patolog%C3%ADa+Cl%C3%ADnica+e+Imagenolog%C3%ADa/@20.6790268,-103.4106715,13z/data=!3m1!5s0x8428ae1162d94179:0x115b1e977b881e1e!4m10!1m2!2m1!1sLa+Unidad+de+Patologia+Guadalajara!3m6!1s0x8428ae6f337d958d:0xcb076a23316a80c1!8m2!3d20.6790268!4d-103.3756526!15sCiJMYSBVbmlkYWQgZGUgUGF0b2xvZ2lhIEd1YWRhbGFqYXJhWiQiImxhIHVuaWRhZCBkZSBwYXRvbG9naWEgZ3VhZGFsYWphcmGSAQttZWRpY2FsX2xhYpoBI0NoWkRTVWhOTUc5blMwVkpRMEZuVFVOWk1uRnRSRXBSRUFF4AEA-gEECGsQNg!16s%2Fg%2F1tx1thwk?entry=ttu&g_ep=EgoyMDI2MDQwMS4wIKXMDSoASAFQAw%3D%3D'
    },
    {
        id: 101,
        name: 'Arena Astros de Jalisco',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'Cheer for the local professional basketball team! A vibrant, safe arena perfect for sports enthusiasts and families.',
        rating: 4.8,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Arena+Astros+Jalisco+Guadalajara'
    },
    {
        id: 102,
        name: 'Parque Avila Camacho',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'A beautiful public park offering boat rides, playgrounds, and plenty of green spaces. Extremely familiar and great for an outdoor picnic.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1498855926480-d98e83099315?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Parque+Avila+Camacho+Guadalajara'
    },
    {
        id: 103,
        name: 'MAZ - Museo de Arte de Zapopan',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'Contemporary art museum in the heart of Zapopan. Offers dynamic exhibitions and cultural workshops for all ages.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1518998053401-b22fb4119864?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Museo+de+Arte+de+Zapopan'
    },
    {
        id: 104,
        name: 'Zoológico Guadalajara',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'One of the most important zoos in Latin America. Features a safari, aquarium, and panoramic cable car ride.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1534567059665-cbbe8b2b640e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Zoologico+Guadalajara'
    },
    {
        id: 105,
        name: 'Parque Los Colomos',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'An iconic forest inside the city. Ideal for jogging, feeding squirrels, and exploring proper Japanese gardens.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Parque+Los+Colomos+Guadalajara'
    },
    {
        id: 106,
        name: 'Pista de Patinaje Bugambilias',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'An indoor ice skating rink located in the Bugambilias mall. Perfect for cooling down and family fun.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1502920514313-52581002a659?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pista+de+Hielo+Bugambilias+Guadalajara'
    },
    {
        id: 107,
        name: 'La Cineteca FICG',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'The premier center for cinema showcasing independent, international, and mainstream films. Completely appropriate for the entire family depending on the screening.',
        rating: 4.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cineteca+FICG+Guadalajara'
    },
    {
        id: 108,
        name: 'KIMA',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'An exciting indoor action-park with trampolines, climbing walls, and obstacle courses that guarantee a fun day out.',
        rating: 4.6,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kima+Guadalajara'
    },
    {
        id: 109,
        name: 'KidZania',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'An interactive mini-city built for kids to role-play professions. Extremely engaging and educational!',
        rating: 4.8,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1566450653303-2614cbb292ea?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=KidZania+Guadalajara'
    },
    {
        id: 110,
        name: 'Panorama',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'A vibrant indoor climbing and bouldering gym. Great for active families and people looking for a physical challenge.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Panorama+climbing+Guadalajara'
    },
    {
        id: 111,
        name: 'Cinery',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'An upscale, comfortable cinema experience offering great food and immersive movie viewings for a relaxed evening.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cinery+Guadalajara'
    },
    {
        id: 112,
        name: 'Biblioteca Pública del Estado',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'A massive, modern public library containing vast collections of books. It has dedicated reading zones and children\'s areas.',
        rating: 4.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Biblioteca+Publica+del+Estado+de+Jalisco'
    },
    {
        id: 113,
        name: 'Vía RecreActiva',
        category: 'Entertainment',
        familyFriendly: true,
        description: 'Every Sunday, major avenues are closed to cars. People come out to cycle, rollerblade, and walk their pets in a completely festive and safe setting.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Via+RecreActiva+Guadalajara'
    }
];
const eventsData = [
    {
        id: 1,
        title: 'Festival Internacional de Cine en Guadalajara',
        culture: 'Mexican / International',
        date: 'April 17–25, 2026',
        location: 'Cineteca FICG',
        description: 'One of the most important film festivals in Latin America bringing together filmmakers, actors, and cinema enthusiasts for screenings and networking.',
        imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/b9nQv2o9rPxXhL1v5'
    },
    {
        id: 2,
        title: 'Diwali Festival de las Luces',
        culture: 'Indian',
        date: 'November 2026',
        location: 'Expo Guadalajara',
        description: 'Celebrate the Indian Festival of Lights with traditional food, dance performances, henna art, and spectacular lighting displays presented by the Indian expat community.',
        imageUrl: 'https://images.unsplash.com/photo-1514222134-b57eaf8ce22e?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/P5LgZ1j8uT8Tj6hWA'
    },
    {
        id: 3,
        title: 'Fiestas de Octubre',
        culture: 'Mexican',
        date: 'October – November 2026',
        location: 'Auditorio Benito Juárez',
        description: 'A massive month-long city-wide celebration showcasing Mexican culture with concerts, regional dances, art exhibits, and a large traditional fair.',
        imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/hPqE1pWz6kH2x7gM8'
    },
    {
        id: 4,
        title: 'Oktoberfest Guadalajara',
        culture: 'German',
        date: 'Mid-October 2026',
        location: 'Club Alemán de Occidente',
        description: 'Authentic Bavarian beer, pretzels, bratwurst, and traditional German folk music in a huge festive tent hosted by the local German club.',
        imageUrl: 'https://images.unsplash.com/photo-1538356111053-748a48e1acb8?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/8JtXz2pMv5QZQzVf7'
    },
    {
        id: 5,
        title: 'Romería de la Virgen de Zapopan',
        culture: 'Mexican',
        date: 'October 12, 2026',
        location: 'Guadalajara Cathedral to Basilica of Zapopan',
        description: 'A deeply significant UNESCO recognized cultural procession involving millions of people accompanying the image of the Virgin of Zapopan on an 8km pilgrimage.',
        imageUrl: 'https://images.unsplash.com/photo-1549488344-c7821eb57d9b?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/Z9zXrXoX5vXZqG5H8'
    },
    {
        id: 6,
        title: 'Matsuri Japones',
        culture: 'Japanese',
        date: 'May 2026',
        location: 'Jardín Japonés, Bosque los Colomos',
        description: 'Experience Japanese culture through an authentic Matsuri with matcha tasting, taiko drumming, and traditional garments within the beautiful Japanese garden.',
        imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/F5PzvG7d5H7Hj8Rj7'
    }
];
