const placesData = [
    {
        id: 1,
        name: 'Café Icarus',
        category: 'Restaurants',
        description: 'Ideal place to have breakfast and brunch with your friends.They are known for their cold brew coffe.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cafe+Icarus+Guadalajara'
    },
    {
        id: 2,
        name: 'Gaspar',
        category: 'Restaurants',
        description: 'Top-rated spots for gourmet burgers and a great bar selection',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Gaspar+Punto+Sao+Paulo+Guadalajara'
    },
    {
        id: 3,
        name: 'Cantalú',
        category: 'Restaurants',
        description: 'A cozy health-focused café specializing in baguettes, chapatas, and "Vaketos" (unique keto-friendly desserts).',
        speaksEnglish: true,
        rating: 4.6,
        vegetarianOptions: true,
        imageUrl: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cantalu+Guadalajara'
    },
    {
        id: 4,
        name: 'Caserol',
        category: 'Restaurants',
        description: 'A charming, "cabin-style" restaurant in Midtown known for its breakfast, high-quality bread, and creative presentation.',
        speaksEnglish: false,
        rating: 4.2,
        vegetarianOptions: true,
        imageUrl: 'https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Caserol+Midtown+Guadalajara'
    },
    {
        id: 5,
        name: 'Campomar',
        category: 'Restaurants',
        description: 'Excellent contemporary Nayarit-style seafood restaurant, perfect for a high-end lunch.',
        rating: 4.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1615141982883-c7da0e69f591?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Campomar+Andares+Guadalajara'
    },
    {
        id: 6,
        name: 'Kaneishi',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Reliable options for sushi and Japanese-inspired bowls.',
        rating: 3.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kaneishi+Guadalajara'
    },
    {
        id: 7,
        name: 'Tacos Providencia',
        vegetarianOptions: false,
        category: 'Restaurants',
        description: 'A local institution. They are famous for their tacos de labio, lengua, and adobada, served with a legendary green salsa.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Providencia+Guadalajara'
    },
    {
        id: 8,
        name: 'Tortas Toño',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'One of the most famous chains for Tortas Ahogadas (pork sandwiches drowned in tomato and chili sauce).',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tortas+Tono+Guadalajara'
    },
    {
        id: 9,
        name: 'Porfirios',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A contemporary Mexican restaurant that reinterprets traditional street food into high-end dishes with a vibrant, festive atmosphere',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Porfirios+Guadalajara'
    },
    {
        id: 10,
        name: 'Nikolaza',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A contemporary Mexican restaurant that reinterprets traditional street food into high-end dishes with a vibrant, festive atmosphere',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1563514995968-07d4b4dd5fa5?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nikolaza+Guadalajara'
    },
    {
        id: 11,
        name: 'Carne Asada Ramón',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Authentic local spot famous for its traditional carne asada and homemade style tortillas.',
        rating: 4.6,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Carne+Asada+Ramon+Guadalajara'
    },
    {
        id: 12,
        name: 'Café Presente',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A cozy café with great coffee and a relaxing atmosphere, perfect for a quiet afternoon or reading.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cafe+Presente+Guadalajara'
    },
    {
        id: 13,
        name: 'Midtown Food Court',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A large modern food court with a variety of affordable options for all tastes, securely located inside Midtown.',
        rating: 4.2,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Midtown+Jalisco+Food+Court'
    },
    {
        id: 14,
        name: 'Gyropolus',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'An authentic Greek restaurant offering delicious gyros, pita bread, and Mediterranean flavors.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Gyropolus+Guadalajara'
    },
    {
        id: 15,
        name: 'Pizza Power',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Located near Punto Sao Paulo, famous for their unique and delicious al pastor meat pizza. An accessible and safe area.',
        rating: 4.4,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pizza+Power+Valparaiso+Guadalajara'
    },
    {
        id: 16,
        name: 'Suehiro',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'One of the oldest and most respected traditional Japanese restaurants in the city.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Suehiro+Guadalajara'
    },
    {
        id: 17,
        name: 'Qin Oriental Food',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Fast, popular, and tasty Chinese food commonly found in major malls and food courts.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Qin+Oriental+Food+Midtown+Guadalajara'
    },
    {
        id: 18,
        name: 'La Artesanal',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A lovely spot featuring artisanal baking, sandwiches, and healthy eating options.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1495474472200-c8f2ba1cbdd0?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Artesanal+Midtown+Guadalajara'
    },
    {
        id: 19,
        name: 'Las Flautas Gdl',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A classic local spot at Valparaíso 2372 known for its incredibly crispy and savory Mexican flautas.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Las+Flautas+Gdl+Valparaiso'
    },
    {
        id: 20,
        name: 'Mar De Cortés',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A premium seafood restaurant offering fresh coastal flavors and a refined dining experience.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1543826173-70651703c5a4?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mar+de+Cortes+Restaurante+Guadalajara'
    },
    {
        id: 21,
        name: 'Tacos Juan',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'An absolute must for locals and foodies looking for incredibly authentic Mexican street tacos.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Juan+Guadalajara'
    },
    {
        id: 22,
        name: 'Carl’s Jr Midtown',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Reliable fast-food burgers and shakes, located conveniently inside the Midtown Plaza.',
        rating: 4.0,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1586816001966-79b736744398?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Carls+Jr+Midtown+Jalisco'
    },
    {
        id: 23,
        name: 'Las Tortas Rika',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Local favorite serving hearty, flavorful tortas in a fast, casual environment.',
        rating: 4.2,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Las+Tortas+Rika+Guadalajara'
    },
    {
        id: 24,
        name: 'Damiana',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A beautiful blend of coffee culture and literature. A quiet place to enjoy a café y libros.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1507133750070-44473e5a40a4?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Damiana+Guadalajara'
    },
    {
        id: 25,
        name: 'Sano Pecado',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Healthy and satisfying. Sano pecado offers guilt-free treats and nutritious main courses.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sano+Pecado+Guadalajara'
    },
    {
        id: 26,
        name: 'Suntory',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'An elegant, high-end teppanyaki and sushi restaurant. Impeccable Japanese service and cuisine.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Suntory+Guadalajara'
    },
    {
        id: 27,
        name: 'Tacos Paris',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Late-night spot popular for straightforward, highly praised street-style tacos.',
        rating: 4.4,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Paris+Guadalajara'
    },
    {
        id: 28,
        name: 'Buffalo Wild Wings',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'American sports bar with a huge selection of wing sauces and multiple screens for sports.',
        rating: 4.1,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1524114664604-cd8133cd67ad?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Buffalo+Wild+Wings+Midtown+Guadalajara'
    },
    {
        id: 29,
        name: 'Mil Caguamas',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Relaxed bar and grill setting offering large portions of seafood and cold beer.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1534068307252-eb0ae9ee6820?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mil+Caguamas+Guadalajara'
    },
    {
        id: 30,
        name: 'Tacos Los Asados (López Mateos)',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Convenient and extremely flavorful tacos right off Lopez Mateos, perfect for a quick bite.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Los+Asados+Lopez+Mateos+Guadalajara'
    },
    {
        id: 31,
        name: 'Nohm Cha',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Trendy spot known for serving unique teas, boba, and snacks with a lively aesthetic.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1525648199074-cee30ba79a4a?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nohm+Cha+Guadalajara'
    },
    {
        id: 32,
        name: 'Santa Lucia 66',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'An intimate dining experience with contemporary cuisine and excellent service.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Santa+Lucia+66+Guadalajara'
    },
    {
        id: 33,
        name: 'Tyrano',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Vibrant dining destination offering hearty meals and specialty crafted sandwiches and cuts.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1508737804141-4c3b688e2546?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tyrano+Guadalajara'
    },
    {
        id: 34,
        name: 'Dainzu',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Very traditional and highly acclaimed Oaxacan food. Perfect to try mole, tlayudas, and authentic regional cuisine.',
        rating: 4.8,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dainzu+Guadalajara'
    },
    {
        id: 35,
        name: 'Frozé',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A stylish spot focused to frozen beverages and refreshing desserts. Amazing for a hot day.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1558222218-b7b54eede3f3?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Froze+Guadalajara'
    },
    {
        id: 36,
        name: 'Vagos',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Cool informal spot with a laidback vibe, great bar foods, and drinks.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Vagos+Guadalajara'
    },
    {
        id: 37,
        name: 'El Terrible Juan',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A hip café and breakfast spot famous for its unique brunch menu and exceptional coffee.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Terrible+Juan+Guadalajara'
    },
    {
        id: 38,
        name: 'Subway',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Quick build-your-own sandwich franchise available at various spots including malls.',
        rating: 3.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Subway+Guadalajara'
    },
    {
        id: 39,
        name: 'El Alto',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'A lively traditional dining option offering an array of Mexican dishes and cold drinks.',
        rating: 4.5,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1514326640560-7d063ef2aed5?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Alto+Guadalajara'
    },
    {
        id: 40,
        name: 'La Lira',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'An iconic butcher shop that has recently opened a fantastic restaurant upstairs serving their high-quality meats.',
        rating: 4.7,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Lira+Carniceria+Guadalajara'
    },
    {
        id: 41,
        name: 'Tacos Al Vapor El Costquito',
        category: 'Restaurants',
        vegetarianOptions: false,
        description: 'Unbeatable comfort food: freshly made "tacos al vapor" (steamed tacos) that are wildly popular locally.',
        rating: 4.6,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tacos+Al+Vapor+El+Costquito+Guadalajara'
    },
    {
        id: 42,
        name: 'Super Salads',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Fresh and customizable salads, paninis, and soups. Perfect for a quick, healthy meal.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Super+Salads+Guadalajara'
    },
    {
        id: 43,
        name: 'Pizza Hut',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Classic international pizza chain providing deep dish pizzas, pasta, and wings.',
        rating: 4.0,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pizza+Hut+Guadalajara'
    },
    {
        id: 44,
        name: 'Sushi Central',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'Trendy sushi spot with fresh ingredients and unique Mexican-inspired sushi rolls and bowls.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sushi+Central+Guadalajara'
    },
    {
        id: 45,
        name: 'Negroni',
        category: 'Restaurants',
        vegetarianOptions: true,
        description: 'A stylish upscale spot in Midtown serving fine Italian cuisine and excellently crafted cocktails.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Negroni+Midtown+Guadalajara'
    },
    {
        id: 46,
        name: 'Nuevo Mundo - Plaza del Sol',
        category: 'Clothing',
        priceRange: '$$',
        description: 'A traditional and reliable department store offering a vast array of clothing, fabrics, and household goods located at Plaza del Sol.',
        rating: 4.1,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nuevo+Mundo+Plaza+del+Sol+Guadalajara'
    },
    {
        id: 47,
        name: 'Lefties',
        category: 'Clothing',
        priceRange: '$',
        description: 'Affordable fast-fashion brand offering trendy clothing and basics. Great for stylish pieces on a budget.',
        rating: 4.0,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lefties+Guadalajara'
    },
    {
        id: 48,
        name: 'Cuidado con el Perro',
        category: 'Clothing',
        priceRange: '$',
        description: 'Highly popular Mexican fast-fashion brand famous for casual wear, graphic tees, and incredibly accessible prices.',
        rating: 4.3,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1528698827591-e19cdd722f0a?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cuidado+con+el+Perro+Guadalajara'
    },
    {
        id: 49,
        name: 'Zara',
        category: 'Clothing',
        priceRange: '$$',
        description: 'Well-known international fast-fashion retailer providing stylish and contemporary clothing for men and women.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1580828369062-81525a7eb84f?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Zara+Guadalajara'
    },
    {
        id: 50,
        name: 'Pull and Bear',
        category: 'Clothing',
        priceRange: '$$',
        description: 'Trendy, youth-focused brand with a casual aesthetic, offering urban clothing and accessories.',
        rating: 4.3,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1564585222527-c2777a5bc6cb?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pull+and+Bear+Guadalajara'
    },
    {
        id: 51,
        name: 'Shasa (Sasha)',
        category: 'Clothing',
        priceRange: '$$',
        description: 'A prominent fashion retailer offering stylish, modern, and youthful womens apparel and accessories.',
        rating: 4.2,
        speaksEnglish: false,
        imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Shasa+Guadalajara'
    },
    {
        id: 52,
        name: 'LOB (Sucursal Midtown Jalisco)',
        category: 'Clothing',
        priceRange: '$$',
        description: 'LOB is a renowned Mexican fashion brand focusing on chic, seasonal, and highly stylish clothing for modern tastes.',
        rating: 4.5,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=LOB+Midtown+Jalisco+Guadalajara'
    },
    {
        id: 53,
        name: 'Human 1931',
        category: 'Clothing',
        priceRange: '$$',
        description: 'A stylish clothing boutique focused on contemporary casual wear and urban fashion statement pieces.',
        rating: 4.4,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1555529771-55ec48dfa2ab?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Human+1931+Guadalajara'
    },
    {
        id: 54,
        name: 'Studio F',
        category: 'Clothing',
        priceRange: '$$$',
        description: 'High-quality Colombian brand highly acclaimed for their phenomenally fitting jeans and premium womens clothing.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Studio+F+Guadalajara'
    },
    {
        id: 55,
        name: 'Loro Piana',
        category: 'Clothing',
        priceRange: '$$$$$',
        description: 'Luxury Italian brand offering unequivocally high-end, sophisticated clothing and accessories crafted from the finest materials.',
        rating: 4.8,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Loro+Piana+Guadalajara'
    },
    {
        id: 56,
        name: 'Pineda Covalin',
        category: 'Clothing',
        priceRange: '$$$',
        description: 'Iconic Mexican design house featuring gorgeous silk scarfs, ties, and clothing deeply inspired by Mexican traditions and art.',
        rating: 4.9,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1574634534894-89d7576c8259?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pineda+Covalin+Guadalajara'
    },
    {
        id: 57,
        name: 'Cloe',
        category: 'Clothing',
        priceRange: '$$',
        description: 'One of the most important Mexican brands for premium handbags, luggage, shoes, and fashionable everyday accessories.',
        rating: 4.6,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cloe+Guadalajara'
    },
    {
        id: 58,
        name: 'Julio',
        category: 'Clothing',
        priceRange: '$$$',
        description: 'Leading Mexican fashion brand dedicated to incredibly elegant and professional womens apparel and sophisticated dresses.',
        rating: 4.7,
        speaksEnglish: true,
        imageUrl: 'https://images.unsplash.com/photo-1560243563-062bfc001d68?w=600&q=80',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Julio+Boutique+Guadalajara'
    }
];

const eventsData = [
    {
        id: 1,
        title: 'Festival Internacional de Cine en Guadalajara',
        culture: 'Mexican / International',
        date: 'April 17–25, 2026',
        location: 'Cineteca FICG',
        description: 'One of the most important film festivals in Latin America bringing together filmmakers, actors, and cinema enthusiasts for screenings and networking.',
        imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/b9nQv2o9rPxXhL1v5'
    },
    {
        id: 2,
        title: 'Diwali Festival de las Luces',
        culture: 'Indian',
        date: 'November 2026',
        location: 'Expo Guadalajara',
        description: 'Celebrate the Indian Festival of Lights with traditional food, dance performances, henna art, and spectacular lighting displays presented by the Indian expat community.',
        imageUrl: 'https://images.unsplash.com/photo-1514222134-b57eaf8ce22e?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/P5LgZ1j8uT8Tj6hWA'
    },
    {
        id: 3,
        title: 'Fiestas de Octubre',
        culture: 'Mexican',
        date: 'October – November 2026',
        location: 'Auditorio Benito Juárez',
        description: 'A massive month-long city-wide celebration showcasing Mexican culture with concerts, regional dances, art exhibits, and a large traditional fair.',
        imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/hPqE1pWz6kH2x7gM8'
    },
    {
        id: 4,
        title: 'Oktoberfest Guadalajara',
        culture: 'German',
        date: 'Mid-October 2026',
        location: 'Club Alemán de Occidente',
        description: 'Authentic Bavarian beer, pretzels, bratwurst, and traditional German folk music in a huge festive tent hosted by the local German club.',
        imageUrl: 'https://images.unsplash.com/photo-1538356111053-748a48e1acb8?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/8JtXz2pMv5QZQzVf7'
    },
    {
        id: 5,
        title: 'Romería de la Virgen de Zapopan',
        culture: 'Mexican',
        date: 'October 12, 2026',
        location: 'Guadalajara Cathedral to Basilica of Zapopan',
        description: 'A deeply significant UNESCO recognized cultural procession involving millions of people accompanying the image of the Virgin of Zapopan on an 8km pilgrimage.',
        imageUrl: 'https://images.unsplash.com/photo-1549488344-c7821eb57d9b?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/Z9zXrXoX5vXZqG5H8'
    },
    {
        id: 6,
        title: 'Matsuri Japones',
        culture: 'Japanese',
        date: 'May 2026',
        location: 'Jardín Japonés, Bosque los Colomos',
        description: 'Experience Japanese culture through an authentic Matsuri with matcha tasting, taiko drumming, and traditional garments within the beautiful Japanese garden.',
        imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80',
        mapsUrl: 'https://goo.gl/maps/F5PzvG7d5H7Hj8Rj7'
    }
];
